export const LIAM_TOP_100_QUESTIONS_TRACK = {
  id: "top-100-questions",
  name: "Liam - Eleven v3",
  title: "100 Common German Questions",
  description: "100 practical German questions with English translations.",
  itemLabel: "questions",
  itemSingular: "question",
  audioUrl: "/audio/liam-top-100-questions-v3.mp3",
  duration: 222.4,
  words: [
    { word: "Wie heißt du?", meaning: "What is your name?", start: 0.14, end: 1.34 },
    { word: "Wie heißen Sie?", meaning: "What is your name?", start: 1.4, end: 2.13 },
    { word: "Wie geht es dir?", meaning: "How are you?", start: 2.92, end: 3.66 },
    { word: "Wie geht es Ihnen?", meaning: "How are you?", start: 4.22, end: 5.03 },
    { word: "Woher kommst du?", meaning: "Where are you from?", start: 6.02, end: 6.89 },
    { word: "Woher kommen Sie?", meaning: "Where are you from?", start: 7.44, end: 8.3 },
    { word: "Wo wohnst du?", meaning: "Where do you live?", start: 9.28, end: 10.12 },
    { word: "Wo wohnen Sie?", meaning: "Where do you live?", start: 10.61, end: 11.48 },
    { word: "Wie alt bist du?", meaning: "How old are you?", start: 12.4, end: 13.23 },
    { word: "Was machst du beruflich?", meaning: "What do you do for a living?", start: 14.08, end: 15.21 },
    { word: "Welche Sprachen sprichst du?", meaning: "Which languages do you speak?", start: 16.14, end: 17.45 },
    { word: "Lernst du Deutsch?", meaning: "Are you learning German?", start: 18.48, end: 19.26 },
    { word: "Bist du neu hier?", meaning: "Are you new here?", start: 20.38, end: 21.2 },
    { word: "Hast du Geschwister?", meaning: "Do you have siblings?", start: 22.3, end: 23.14 },
    { word: "Bist du verheiratet?", meaning: "Are you married?", start: 24.3, end: 25.31 },
    { word: "Was machst du gern?", meaning: "What do you like doing?", start: 26.5, end: 27.37 },
    { word: "Was sind deine Hobbys?", meaning: "What are your hobbies?", start: 28.32, end: 29.41 },
    { word: "Was ist dein Lieblingsessen?", meaning: "What is your favourite food?", start: 30.57, end: 31.92 },
    { word: "Wie war dein Tag?", meaning: "How was your day?", start: 33.06, end: 33.94 },
    { word: "Was hast du heute gemacht?", meaning: "What did you do today?", start: 35.06, end: 36.26 },
    { word: "Was machst du gerade?", meaning: "What are you doing right now?", start: 37.42, end: 38.34 },
    { word: "Was möchtest du machen?", meaning: "What would you like to do?", start: 39.56, end: 40.64 },
    { word: "Was möchtest du essen?", meaning: "What would you like to eat?", start: 41.78, end: 42.8 },
    { word: "Was möchtest du trinken?", meaning: "What would you like to drink?", start: 43.92, end: 45.18 },
    { word: "Hast du Hunger?", meaning: "Are you hungry?", start: 46.36, end: 46.94 },
    { word: "Hast du Durst?", meaning: "Are you thirsty?", start: 48.04, end: 48.88 },
    { word: "Möchtest du etwas trinken?", meaning: "Would you like something to drink?", start: 50, end: 51.24 },
    { word: "Schmeckt dir das Essen?", meaning: "Do you like the food?", start: 52.46, end: 53.42 },
    { word: "Kannst du kochen?", meaning: "Can you cook?", start: 54.6, end: 55.34 },
    { word: "Was gibt es zum Essen?", meaning: "What is there to eat?", start: 56.66, end: 57.72 },
    { word: "Wie spät ist es?", meaning: "What time is it?", start: 58.9, end: 59.76 },
    { word: "Welcher Tag ist heute?", meaning: "What day is it today?", start: 60.9, end: 62.06 },
    { word: "Welches Datum ist heute?", meaning: "What is today’s date?", start: 63.18, end: 64.4 },
    { word: "Wann beginnt es?", meaning: "When does it begin?", start: 65.54, end: 66.34 },
    { word: "Wann bist du fertig?", meaning: "When will you be finished?", start: 67.52, end: 68.52 },
    { word: "Wann kommst du zurück?", meaning: "When are you coming back?", start: 69.84, end: 70.86 },
    { word: "Wie lange dauert das?", meaning: "How long does that take?", start: 72.09, end: 73.1 },
    { word: "Hast du heute Zeit?", meaning: "Do you have time today?", start: 74.26, end: 75.28 },
    { word: "Passt es dir morgen?", meaning: "Does tomorrow suit you?", start: 76.54, end: 77.5 },
    { word: "Können wir uns später treffen?", meaning: "Can we meet later?", start: 78.68, end: 79.97 },
    { word: "Wo bist du?", meaning: "Where are you?", start: 81.18, end: 82.02 },
    { word: "Wohin gehst du?", meaning: "Where are you going?", start: 82.86, end: 83.74 },
    { word: "Wo ist die Toilette?", meaning: "Where is the toilet?", start: 84.82, end: 85.78 },
    { word: "Wo ist der Bahnhof?", meaning: "Where is the train station?", start: 87.04, end: 88.02 },
    { word: "Wie komme ich dorthin?", meaning: "How do I get there?", start: 89.24, end: 90.26 },
    { word: "Ist es weit von hier?", meaning: "Is it far from here?", start: 91.48, end: 92.54 },
    { word: "Welchen Bus muss ich nehmen?", meaning: "Which bus do I need to take?", start: 93.9, end: 95.22 },
    { word: "Wann fährt der nächste Zug?", meaning: "When does the next train leave?", start: 96.4, end: 97.66 },
    { word: "Wo muss ich umsteigen?", meaning: "Where do I need to change?", start: 98.92, end: 100 },
    { word: "Ist dieser Platz frei?", meaning: "Is this seat free?", start: 101.28, end: 102.38 },
    { word: "Wie viel kostet das?", meaning: "How much does that cost?", start: 103.63, end: 104.73 },
    { word: "Kann ich mit Karte bezahlen?", meaning: "Can I pay by card?", start: 105.9, end: 107.32 },
    { word: "Haben Sie etwas Günstigeres?", meaning: "Do you have something cheaper?", start: 108.46, end: 109.82 },
    { word: "Kann ich das anprobieren?", meaning: "Can I try that on?", start: 111.05, end: 112.18 },
    { word: "Welche Größe haben Sie?", meaning: "What size do you have?", start: 113.39, end: 114.61 },
    { word: "Gibt es das in einer anderen Farbe?", meaning: "Is that available in another colour?", start: 115.9, end: 117.57 },
    { word: "Wo ist die Kasse?", meaning: "Where is the checkout?", start: 118.9, end: 120.98 },
    { word: "Kann ich eine Quittung bekommen?", meaning: "Can I get a receipt?", start: 121, end: 122.36 },
    { word: "Kann ich das zurückgeben?", meaning: "Can I return that?", start: 123.58, end: 124.74 },
    { word: "Ist das im Angebot?", meaning: "Is that on sale?", start: 126.02, end: 127.02 },
    { word: "Kannst du mir helfen?", meaning: "Can you help me?", start: 128.32, end: 129.19 },
    { word: "Können Sie mir bitte helfen?", meaning: "Could you please help me?", start: 130.56, end: 131.94 },
    { word: "Was bedeutet dieses Wort?", meaning: "What does this word mean?", start: 133.24, end: 134.56 },
    { word: "Wie sagt man das auf Deutsch?", meaning: "How do you say that in German?", start: 135.82, end: 137.12 },
    { word: "Wie schreibt man das?", meaning: "How do you spell that?", start: 138.46, end: 139.39 },
    { word: "Wie spricht man das aus?", meaning: "How do you pronounce that?", start: 140.7, end: 141.86 },
    { word: "Können Sie das wiederholen?", meaning: "Could you repeat that?", start: 143.18, end: 144.38 },
    { word: "Kannst du langsamer sprechen?", meaning: "Can you speak more slowly?", start: 145.6, end: 146.92 },
    { word: "Hast du das verstanden?", meaning: "Did you understand that?", start: 148.22, end: 149.26 },
    { word: "Was meinst du damit?", meaning: "What do you mean by that?", start: 150.68, end: 151.7 },
    { word: "Warum ist das so?", meaning: "Why is that so?", start: 152.9, end: 153.82 },
    { word: "Was ist passiert?", meaning: "What happened?", start: 155.18, end: 156.06 },
    { word: "Was ist das Problem?", meaning: "What is the problem?", start: 157.42, end: 158.38 },
    { word: "Wie können wir das lösen?", meaning: "How can we solve that?", start: 159.74, end: 160.94 },
    { word: "Was sollen wir jetzt tun?", meaning: "What should we do now?", start: 162.3, end: 163.48 },
    { word: "Was denkst du darüber?", meaning: "What do you think about it?", start: 164.8, end: 165.8 },
    { word: "Wie findest du diese Idee?", meaning: "What do you think of this idea?", start: 167.2, end: 168.4 },
    { word: "Bist du damit einverstanden?", meaning: "Do you agree with that?", start: 169.82, end: 171.1 },
    { word: "Warum denkst du das?", meaning: "Why do you think that?", start: 172.44, end: 173.5 },
    { word: "Welche Möglichkeit ist besser?", meaning: "Which option is better?", start: 174.89, end: 176.38 },
    { word: "Wie fühlst du dich?", meaning: "How do you feel?", start: 177.8, end: 178.609 },
    { word: "Bist du müde?", meaning: "Are you tired?", start: 179.9, end: 180.58 },
    { word: "Bist du glücklich?", meaning: "Are you happy?", start: 181.9, end: 182.78 },
    { word: "Was macht dir Sorgen?", meaning: "What worries you?", start: 184.02, end: 185.04 },
    { word: "Hast du Angst?", meaning: "Are you afraid?", start: 186.32, end: 187.14 },
    { word: "Warum bist du traurig?", meaning: "Why are you sad?", start: 188.38, end: 189.46 },
    { word: "Bist du zufrieden?", meaning: "Are you satisfied?", start: 190.84, end: 191.74 },
    { word: "Was macht dich glücklich?", meaning: "What makes you happy?", start: 193.1, end: 194.269 },
    { word: "Kann ich etwas für dich tun?", meaning: "Can I do anything for you?", start: 195.52, end: 196.82 },
    { word: "Geht es dir besser?", meaning: "Are you feeling better?", start: 198.04, end: 198.84 },
    { word: "Wie sieht er aus?", meaning: "What does he look like?", start: 200.3, end: 201.18 },
    { word: "Wie ist sie?", meaning: "What is she like?", start: 202.34, end: 203.1 },
    { word: "Was trägt er?", meaning: "What is he wearing?", start: 204.2, end: 205.01 },
    { word: "Welche Farbe hat das?", meaning: "What colour is that?", start: 206.28, end: 207.42 },
    { word: "Wie groß ist die Wohnung?", meaning: "How large is the apartment?", start: 208.74, end: 209.88 },
    { word: "Wie funktioniert dieses Gerät?", meaning: "How does this device work?", start: 211.18, end: 212.62 },
    { word: "Wofür wird das verwendet?", meaning: "What is that used for?", start: 213.9, end: 215.18 },
    { word: "Was ist der Unterschied?", meaning: "What is the difference?", start: 216.45, end: 217.62 },
    { word: "Welche Vorteile hat das?", meaning: "What advantages does that have?", start: 218.94, end: 220.2 },
    { word: "Hast du noch Fragen?", meaning: "Do you have any more questions?", start: 221.5, end: 222.4 },
  ],
};
