export const LIAM_TOP_100_INTRODUCTION_SENTENCES_TRACK = {
  id: "top-100-introduction-sentences",
  name: "Liam - Eleven v3",
  title: "100 German Introduction Sentences",
  description: "100 German introduction sentences with English translations.",
  itemLabel: "sentences",
  itemSingular: "sentence",
  audioUrl: "/audio/liam-top-100-introduction-sentences-v3.mp3",
  duration: 167.68,
  words: [
    { word: "Hallo!", meaning: "Hello!", start: 0.1, end: 0.52 },
    { word: "Guten Morgen!", meaning: "Good morning!", start: 0.78, end: 1.48 },
    { word: "Guten Tag!", meaning: "Good day!", start: 1.78, end: 2.46 },
    { word: "Guten Abend!", meaning: "Good evening!", start: 2.76, end: 3.369 },
    { word: "Herzlich willkommen!", meaning: "A warm welcome!", start: 3.68, end: 4.56 },
    { word: "Darf ich mich vorstellen?", meaning: "May I introduce myself?", start: 5.02, end: 6.01 },
    { word: "Ich möchte mich kurz vorstellen.", meaning: "I would like to introduce myself briefly.", start: 6.48, end: 7.9 },
    { word: "Mein Name ist [Name].", meaning: "My name is [name].", start: 8.34, end: 9.6 },
    { word: "Ich heiße [Name].", meaning: "My name is [name].", start: 9.64, end: 10.55 },
    { word: "Ich bin [Name].", meaning: "I am [name].", start: 10.56, end: 11.52 },
    { word: "Wie heißen Sie?", meaning: "What is your name?", start: 11.6, end: 12.27 },
    { word: "Wie heißt du?", meaning: "What is your name?", start: 12.78, end: 13.34 },
    { word: "Freut mich, Sie kennenzulernen.", meaning: "Nice to meet you.", start: 13.94, end: 15.24 },
    { word: "Freut mich, dich kennenzulernen.", meaning: "Nice to meet you.", start: 15.76, end: 17.5 },
    { word: "Schön, Sie kennenzulernen.", meaning: "It is nice to meet you.", start: 17.64, end: 18.75 },
    { word: "Schön, dich kennenzulernen.", meaning: "It is nice to meet you.", start: 19.22, end: 20.9 },
    { word: "Es freut mich, hier zu sein.", meaning: "I am pleased to be here.", start: 20.94, end: 22.3 },
    { word: "Vielen Dank für die Einladung.", meaning: "Thank you very much for the invitation.", start: 22.86, end: 24.24 },
    { word: "Danke, dass ich mich vorstellen darf.", meaning: "Thank you for letting me introduce myself.", start: 24.76, end: 26.32 },
    { word: "Ich komme aus [Land].", meaning: "I come from [country].", start: 26.82, end: 28.08 },
    { word: "Ich stamme aus [Land].", meaning: "I am originally from [country].", start: 28.14, end: 29.48 },
    { word: "Woher kommen Sie?", meaning: "Where do you come from?", start: 29.53, end: 30.22 },
    { word: "Woher kommst du?", meaning: "Where do you come from?", start: 30.72, end: 31.46 },
    { word: "Ich bin in [Stadt] geboren.", meaning: "I was born in [city].", start: 32.06, end: 33.66 },
    { word: "Ich bin in [Stadt] aufgewachsen.", meaning: "I grew up in [city].", start: 34.1, end: 35.9 },
    { word: "Ich wohne in [Stadt].", meaning: "I live in [city].", start: 36.38, end: 37.54 },
    { word: "Ich lebe derzeit in [Stadt].", meaning: "I currently live in [city].", start: 37.56, end: 39.21 },
    { word: "Wo wohnen Sie?", meaning: "Where do you live?", start: 39.3, end: 40.4 },
    { word: "Wo wohnst du?", meaning: "Where do you live?", start: 40.46, end: 41.14 },
    { word: "Ich wohne seit zwei Jahren hier.", meaning: "I have lived here for two years.", start: 41.78, end: 43.32 },
    { word: "Ich bin neu hier.", meaning: "I am new here.", start: 43.74, end: 44.6 },
    { word: "Ich bin erst kürzlich hierhergezogen.", meaning: "I recently moved here.", start: 45.1, end: 47.34 },
    { word: "Ich bin [Zahl] Jahre alt.", meaning: "I am [number] years old.", start: 47.4, end: 49.32 },
    { word: "Wie alt sind Sie?", meaning: "How old are you?", start: 49.38, end: 50.54 },
    { word: "Wie alt bist du?", meaning: "How old are you?", start: 50.6, end: 51.3 },
    { word: "Mein Geburtstag ist am [Datum].", meaning: "My birthday is on [date].", start: 51.9, end: 53.61 },
    { word: "Ich bin verheiratet.", meaning: "I am married.", start: 53.64, end: 54.67 },
    { word: "Ich bin ledig.", meaning: "I am single.", start: 55.08, end: 55.86 },
    { word: "Ich lebe mit meiner Familie zusammen.", meaning: "I live with my family.", start: 56.48, end: 58.21 },
    { word: "Ich habe zwei Geschwister.", meaning: "I have two siblings.", start: 58.68, end: 59.88 },
    { word: "Ich habe einen Bruder.", meaning: "I have a brother.", start: 60.36, end: 61.32 },
    { word: "Ich habe eine Schwester.", meaning: "I have a sister.", start: 61.78, end: 62.8 },
    { word: "Ich habe keine Kinder.", meaning: "I do not have any children.", start: 63.32, end: 64.34 },
    { word: "Ich habe zwei Kinder.", meaning: "I have two children.", start: 64.8, end: 65.82 },
    { word: "Ich spreche Arabisch und Englisch.", meaning: "I speak Arabic and English.", start: 66.36, end: 68.06 },
    { word: "Welche Sprachen sprechen Sie?", meaning: "Which languages do you speak?", start: 68.6, end: 69.85 },
    { word: "Welche Sprachen sprichst du?", meaning: "Which languages do you speak?", start: 70.34, end: 71.58 },
    { word: "Ich lerne gerade Deutsch.", meaning: "I am currently learning German.", start: 72.2, end: 73.4 },
    { word: "Ich spreche ein wenig Deutsch.", meaning: "I speak a little German.", start: 73.92, end: 75.18 },
    { word: "Mein Deutsch ist noch nicht perfekt.", meaning: "My German is not perfect yet.", start: 75.66, end: 77.16 },
    { word: "Ich möchte mein Deutsch verbessern.", meaning: "I would like to improve my German.", start: 77.68, end: 79.6 },
    { word: "Können Sie bitte langsamer sprechen?", meaning: "Could you please speak more slowly?", start: 79.66, end: 81.15 },
    { word: "Was machen Sie beruflich?", meaning: "What do you do professionally?", start: 81.8, end: 82.92 },
    { word: "Was machst du beruflich?", meaning: "What do you do for a living?", start: 83.5, end: 84.54 },
    { word: "Ich arbeite als Ingenieur.", meaning: "I work as an engineer.", start: 85.2, end: 86.86 },
    { word: "Ich bin von Beruf Ingenieur.", meaning: "I am an engineer by profession.", start: 86.9, end: 88.28 },
    { word: "Ich arbeite im IT-Bereich.", meaning: "I work in the IT field.", start: 88.96, end: 90.55 },
    { word: "Ich arbeite bei [Firma].", meaning: "I work at [company].", start: 91.08, end: 92.25 },
    { word: "Ich arbeite seit fünf Jahren dort.", meaning: "I have worked there for five years.", start: 92.3, end: 93.93 },
    { word: "Ich bin selbstständig.", meaning: "I am self-employed.", start: 94.52, end: 95.86 },
    { word: "Ich suche derzeit eine neue Stelle.", meaning: "I am currently looking for a new job.", start: 95.92, end: 97.94 },
    { word: "Ich bin Student.", meaning: "I am a male student.", start: 97.98, end: 98.79 },
    { word: "Ich bin Studentin.", meaning: "I am a female student.", start: 99.22, end: 100.06 },
    { word: "Ich studiere Informatik.", meaning: "I study computer science.", start: 100.62, end: 101.76 },
    { word: "Ich besuche derzeit einen Deutschkurs.", meaning: "I am currently attending a German course.", start: 102.28, end: 104 },
    { word: "Was studieren Sie?", meaning: "What do you study?", start: 104.66, end: 105.42 },
    { word: "Was studierst du?", meaning: "What do you study?", start: 105.98, end: 106.76 },
    { word: "Ich interessiere mich für Technologie.", meaning: "I am interested in technology.", start: 107.38, end: 109 },
    { word: "Meine Hobbys sind Lesen und Reisen.", meaning: "My hobbies are reading and travelling.", start: 109.64, end: 111.4 },
    { word: "Was machen Sie gern in Ihrer Freizeit?", meaning: "What do you like doing in your free time?", start: 112.1, end: 113.76 },
    { word: "Was machst du gern in deiner Freizeit?", meaning: "What do you like doing in your free time?", start: 114.42, end: 115.98 },
    { word: "In meiner Freizeit lese ich gern.", meaning: "I like reading in my free time.", start: 116.68, end: 118.28 },
    { word: "Ich höre gern Musik.", meaning: "I like listening to music.", start: 118.82, end: 119.78 },
    { word: "Ich sehe gern Filme.", meaning: "I like watching films.", start: 120.32, end: 121.28 },
    { word: "Ich treibe regelmäßig Sport.", meaning: "I exercise regularly.", start: 121.8, end: 123.22 },
    { word: "Ich gehe gern spazieren.", meaning: "I like going for walks.", start: 123.7, end: 124.82 },
    { word: "Ich reise sehr gern.", meaning: "I really enjoy travelling.", start: 125.36, end: 126.34 },
    { word: "Ich koche gern.", meaning: "I like cooking.", start: 126.8, end: 127.52 },
    { word: "Ich verbringe gern Zeit mit meiner Familie.", meaning: "I like spending time with my family.", start: 128.039, end: 129.88 },
    { word: "Mein Lieblingshobby ist Fotografieren.", meaning: "My favourite hobby is photography.", start: 130.44, end: 132.17 },
    { word: "Wie geht es Ihnen?", meaning: "How are you?", start: 132.96, end: 133.67 },
    { word: "Wie geht es dir?", meaning: "How are you?", start: 134.24, end: 134.86 },
    { word: "Mir geht es gut, danke.", meaning: "I am fine, thank you.", start: 135.6, end: 136.62 },
    { word: "Und Ihnen?", meaning: "And you?", start: 137.12, end: 137.57 },
    { word: "Und dir?", meaning: "And you?", start: 138.12, end: 138.46 },
    { word: "Was führt Sie hierher?", meaning: "What brings you here?", start: 139.24, end: 140.94 },
    { word: "Was führt dich hierher?", meaning: "What brings you here?", start: 141.06, end: 141.94 },
    { word: "Ich bin wegen der Arbeit hier.", meaning: "I am here because of work.", start: 142.7, end: 144.4 },
    { word: "Ich bin geschäftlich hier.", meaning: "I am here on business.", start: 144.46, end: 145.98 },
    { word: "Ich bin im Urlaub hier.", meaning: "I am here on holiday.", start: 146.04, end: 147.579 },
    { word: "Ich freue mich auf die Zusammenarbeit.", meaning: "I look forward to working together.", start: 147.62, end: 149.22 },
    { word: "Ich freue mich darauf, Sie besser kennenzulernen.", meaning: "I look forward to getting to know you better.", start: 149.82, end: 152.28 },
    { word: "Ich hoffe, wir bleiben in Kontakt.", meaning: "I hope we stay in touch.", start: 152.34, end: 154.26 },
    { word: "Hier ist meine Telefonnummer.", meaning: "Here is my telephone number.", start: 154.3, end: 156.04 },
    { word: "Hier ist meine E-Mail-Adresse.", meaning: "Here is my email address.", start: 156.1, end: 158.06 },
    { word: "Sie können mich jederzeit kontaktieren.", meaning: "You can contact me at any time.", start: 158.1, end: 160.4 },
    { word: "Du kannst mich gern kontaktieren.", meaning: "You are welcome to contact me.", start: 160.43, end: 162.399 },
    { word: "Haben Sie noch Fragen?", meaning: "Do you have any more questions?", start: 162.43, end: 163.329 },
    { word: "Das war eine kurze Vorstellung von mir.", meaning: "That was a brief introduction about me.", start: 164, end: 165.7 },
    { word: "Vielen Dank für Ihre Aufmerksamkeit.", meaning: "Thank you for your attention.", start: 166.18, end: 167.68 },
  ],
};
