export const LIAM_TOP_100_EXPRESSION_SENTENCES_TRACK = {
  id: "top-100-expression-sentences",
  name: "Liam - Eleven v3",
  title: "100 German Expression Sentences",
  description: "100 German sentences for expressing ideas, opinions, feelings, and descriptions.",
  itemLabel: "sentences",
  itemSingular: "sentence",
  audioUrl: "/audio/liam-top-100-expression-sentences-v3.mp3",
  duration: 298.38,
  words: [
    { word: "Ich denke, dass das eine gute Idee ist.", meaning: "I think that is a good idea.", start: 0.2, end: 2.04 },
    { word: "Ich glaube, dass das möglich ist.", meaning: "I believe that is possible.", start: 2.64, end: 4.1 },
    { word: "Meiner Meinung nach ist das wichtig.", meaning: "In my opinion, that is important.", start: 5.04, end: 6.8 },
    { word: "Ich bin der Meinung, dass wir warten sollten.", meaning: "I think that we should wait.", start: 7.6, end: 9.36 },
    { word: "Ich finde diese Idee interessant.", meaning: "I find this idea interesting.", start: 10.42, end: 11.98 },
    { word: "Für mich ist das die beste Lösung.", meaning: "For me, that is the best solution.", start: 12.9, end: 15.12 },
    { word: "Aus meiner Sicht ist das richtig.", meaning: "From my perspective, that is correct.", start: 15.96, end: 17.74 },
    { word: "Soweit ich weiß, stimmt das.", meaning: "As far as I know, that is correct.", start: 18.62, end: 20.26 },
    { word: "Ich bin mir nicht sicher.", meaning: "I am not sure.", start: 21.22, end: 22.12 },
    { word: "Ich habe Zweifel daran.", meaning: "I have doubts about it.", start: 22.96, end: 24.15 },
    { word: "Ich stimme dir zu.", meaning: "I agree with you.", start: 25.16, end: 25.96 },
    { word: "Ich stimme Ihnen vollkommen zu.", meaning: "I completely agree with you.", start: 27.04, end: 28.68 },
    { word: "Da bin ich anderer Meinung.", meaning: "I have a different opinion about that.", start: 29.84, end: 31.18 },
    { word: "Ich sehe das anders.", meaning: "I see it differently.", start: 31.98, end: 32.9 },
    { word: "Das kann ich gut verstehen.", meaning: "I can understand that well.", start: 34.04, end: 35.66 },
    { word: "Das ergibt für mich Sinn.", meaning: "That makes sense to me.", start: 36.58, end: 37.9 },
    { word: "Das überzeugt mich nicht.", meaning: "That does not convince me.", start: 39.08, end: 40.32 },
    { word: "Das hängt von der Situation ab.", meaning: "That depends on the situation.", start: 41.41, end: 43.08 },
    { word: "Es gibt verschiedene Möglichkeiten.", meaning: "There are different possibilities.", start: 44.3, end: 47.22 },
    { word: "Wir sollten beide Seiten berücksichtigen.", meaning: "We should consider both sides.", start: 47.26, end: 50.28 },
    { word: "Der wichtigste Punkt ist, dass wir eine Lösung finden.", meaning: "The most important point is that we find a solution.", start: 50.4, end: 53.3 },
    { word: "Das Hauptproblem besteht darin, dass wir wenig Zeit haben.", meaning: "The main problem is that we have little time.", start: 54.46, end: 58.94 },
    { word: "Der Vorteil ist, dass es einfach funktioniert.", meaning: "The advantage is that it works easily.", start: 58.98, end: 61.6 },
    { word: "Der Nachteil ist, dass es teuer ist.", meaning: "The disadvantage is that it is expensive.", start: 62.72, end: 64.9 },
    { word: "Das Ziel besteht darin, die Situation zu verbessern.", meaning: "The goal is to improve the situation.", start: 66.24, end: 69.4 },
    { word: "Der Grund dafür ist nicht klar.", meaning: "The reason for that is not clear.", start: 70.61, end: 72.34 },
    { word: "Das bedeutet, dass wir etwas ändern müssen.", meaning: "That means that we must change something.", start: 73.62, end: 76.04 },
    { word: "Das zeigt, wie wichtig dieses Thema ist.", meaning: "That shows how important this topic is.", start: 77.22, end: 79.76 },
    { word: "Ein gutes Beispiel dafür ist dieses Projekt.", meaning: "A good example of this is this project.", start: 81.1, end: 83.8 },
    { word: "Im Allgemeinen funktioniert das sehr gut.", meaning: "In general, that works very well.", start: 85.18, end: 87.66 },
    { word: "Einerseits ist es praktisch, andererseits ist es teuer.", meaning: "On the one hand, it is practical; on the other hand, it is expensive.", start: 88.98, end: 92.56 },
    { word: "Im Vergleich dazu ist diese Lösung besser.", meaning: "In comparison, this solution is better.", start: 93.76, end: 97.88 },
    { word: "Im Gegensatz dazu ist die andere Möglichkeit einfacher.", meaning: "In contrast, the other option is easier.", start: 97.94, end: 101.32 },
    { word: "Deshalb halte ich diese Entscheidung für richtig.", meaning: "Therefore, I consider this decision correct.", start: 102.46, end: 105.14 },
    { word: "Trotzdem sollten wir vorsichtig sein.", meaning: "Nevertheless, we should be careful.", start: 106.38, end: 108.58 },
    { word: "Außerdem müssen wir die Kosten berücksichtigen.", meaning: "In addition, we must consider the costs.", start: 109.88, end: 113.56 },
    { word: "Zusammenfassend kann man sagen, dass es erfolgreich war.", meaning: "In summary, one can say that it was successful.", start: 113.62, end: 116.58 },
    { word: "Ich verstehe, was du meinst.", meaning: "I understand what you mean.", start: 117.72, end: 119.039 },
    { word: "Könntest du das genauer erklären?", meaning: "Could you explain that more precisely?", start: 120.22, end: 121.84 },
    { word: "Was genau meinst du damit?", meaning: "What exactly do you mean by that?", start: 122.94, end: 124.34 },
    { word: "Ich möchte etwas hinzufügen.", meaning: "I would like to add something.", start: 125.84, end: 127.36 },
    { word: "Darf ich meine Meinung dazu sagen?", meaning: "May I give my opinion on that?", start: 128.32, end: 129.979 },
    { word: "Ich möchte diesen Punkt kurz erklären.", meaning: "I would like to explain this point briefly.", start: 131.2, end: 133.3 },
    { word: "Lass mich ein Beispiel geben.", meaning: "Let me give an example.", start: 134.54, end: 135.76 },
    { word: "Das ist nicht genau das, was ich meine.", meaning: "That is not exactly what I mean.", start: 136.8, end: 138.72 },
    { word: "Mit anderen Worten, wir brauchen mehr Zeit.", meaning: "In other words, we need more time.", start: 139.56, end: 142.02 },
    { word: "Es geht hauptsächlich um die Qualität.", meaning: "It is mainly about quality.", start: 143.28, end: 145.18 },
    { word: "Dieses Thema betrifft uns alle.", meaning: "This topic concerns all of us.", start: 146.38, end: 148.88 },
    { word: "Darüber müssen wir noch sprechen.", meaning: "We still need to talk about that.", start: 148.92, end: 151.86 },
    { word: "Darüber habe ich noch nicht nachgedacht.", meaning: "I have not thought about that yet.", start: 151.92, end: 153.94 },
    { word: "Ich freue mich darüber.", meaning: "I am happy about it.", start: 155.06, end: 156.08 },
    { word: "Ich bin sehr glücklich.", meaning: "I am very happy.", start: 157, end: 158.06 },
    { word: "Ich bin heute gut gelaunt.", meaning: "I am in a good mood today.", start: 159.16, end: 160.46 },
    { word: "Ich bin stolz auf dich.", meaning: "I am proud of you.", start: 161.42, end: 162.56 },
    { word: "Ich bin mit dem Ergebnis zufrieden.", meaning: "I am satisfied with the result.", start: 163.56, end: 165.34 },
    { word: "Ich bin davon begeistert.", meaning: "I am excited about it.", start: 166.52, end: 167.76 },
    { word: "Das macht mich glücklich.", meaning: "That makes me happy.", start: 168.86, end: 169.88 },
    { word: "Ich fühle mich heute nicht gut.", meaning: "I do not feel well today.", start: 171.02, end: 172.36 },
    { word: "Ich bin etwas traurig.", meaning: "I am a little sad.", start: 173.42, end: 174.68 },
    { word: "Ich bin darüber enttäuscht.", meaning: "I am disappointed about it.", start: 175.8, end: 177.08 },
    { word: "Das macht mir Sorgen.", meaning: "That worries me.", start: 178.16, end: 179.18 },
    { word: "Ich habe ein wenig Angst.", meaning: "I am a little afraid.", start: 180.28, end: 181.54 },
    { word: "Ich bin nervös wegen des Gesprächs.", meaning: "I am nervous about the conversation.", start: 182.66, end: 184.48 },
    { word: "Ich bin im Moment gestresst.", meaning: "I am stressed at the moment.", start: 185.74, end: 187.1 },
    { word: "Ich bin sehr müde.", meaning: "I am very tired.", start: 188.32, end: 189.36 },
    { word: "Ich bin überrascht, dass es funktioniert hat.", meaning: "I am surprised that it worked.", start: 190.6, end: 192.82 },
    { word: "Das ärgert mich.", meaning: "That annoys me.", start: 194.08, end: 194.99 },
    { word: "Ich bin wütend darüber.", meaning: "I am angry about it.", start: 196.32, end: 197.46 },
    { word: "Ich fühle mich erleichtert.", meaning: "I feel relieved.", start: 198.78, end: 200.06 },
    { word: "Ich hoffe, dass alles gut geht.", meaning: "I hope that everything goes well.", start: 201.36, end: 202.78 },
    { word: "Er ist ein freundlicher Mensch.", meaning: "He is a friendly person.", start: 203.96, end: 205.46 },
    { word: "Sie ist sehr ruhig und geduldig.", meaning: "She is very calm and patient.", start: 206.72, end: 208.46 },
    { word: "Er ist zuverlässig und arbeitet sorgfältig.", meaning: "He is reliable and works carefully.", start: 209.66, end: 212.48 },
    { word: "Sie ist offen und spricht gern mit anderen.", meaning: "She is open and likes talking to others.", start: 213.7, end: 216.06 },
    { word: "Er wirkt ein wenig nervös.", meaning: "He seems a little nervous.", start: 217.26, end: 219.26 },
    { word: "Sie sieht heute glücklich aus.", meaning: "She looks happy today.", start: 219.9, end: 221.32 },
    { word: "Er hat viel Erfahrung.", meaning: "He has a lot of experience.", start: 222.7, end: 224 },
    { word: "Sie versteht ihre Arbeit sehr gut.", meaning: "She understands her work very well.", start: 225.18, end: 226.96 },
    { word: "Er hilft anderen Menschen gern.", meaning: "He likes helping other people.", start: 228.22, end: 229.8 },
    { word: "Sie hat einen guten Sinn für Humor.", meaning: "She has a good sense of humour.", start: 230.92, end: 232.72 },
    { word: "Wir haben ähnliche Interessen.", meaning: "We have similar interests.", start: 234.1, end: 235.49 },
    { word: "Ich kenne ihn schon seit vielen Jahren.", meaning: "I have known him for many years.", start: 236.88, end: 238.609 },
    { word: "Sie ist eine gute Freundin von mir.", meaning: "She is a good friend of mine.", start: 239.86, end: 241.52 },
    { word: "Er ist für dieses Projekt verantwortlich.", meaning: "He is responsible for this project.", start: 242.76, end: 244.66 },
    { word: "Sie spielt eine wichtige Rolle im Team.", meaning: "She plays an important role in the team.", start: 246, end: 247.8 },
    { word: "Das Haus ist groß und modern.", meaning: "The house is large and modern.", start: 249.18, end: 250.94 },
    { word: "Das Zimmer ist hell und sauber.", meaning: "The room is bright and clean.", start: 252.2, end: 253.9 },
    { word: "Die Wohnung liegt in einer ruhigen Gegend.", meaning: "The apartment is located in a quiet area.", start: 255.18, end: 257 },
    { word: "Das Auto sieht sehr elegant aus.", meaning: "The car looks very elegant.", start: 258.269, end: 260.12 },
    { word: "Dieses Gerät ist einfach zu bedienen.", meaning: "This device is easy to use.", start: 261.54, end: 263.38 },
    { word: "Das Buch ist interessant und leicht zu verstehen.", meaning: "The book is interesting and easy to understand.", start: 264.6, end: 267.42 },
    { word: "Der Film war spannend, aber etwas zu lang.", meaning: "The film was exciting but a little too long.", start: 268.8, end: 271.26 },
    { word: "Das Essen schmeckt sehr gut.", meaning: "The food tastes very good.", start: 272.54, end: 273.98 },
    { word: "Die Aufgabe ist schwieriger als erwartet.", meaning: "The task is more difficult than expected.", start: 275.32, end: 277.46 },
    { word: "Das Problem ist größer, als wir gedacht haben.", meaning: "The problem is bigger than we thought.", start: 278.6, end: 280.86 },
    { word: "Die Situation hat sich deutlich verbessert.", meaning: "The situation has improved significantly.", start: 282.18, end: 284.3 },
    { word: "Das Ergebnis entspricht unseren Erwartungen.", meaning: "The result meets our expectations.", start: 285.5, end: 288.2 },
    { word: "Dieses Produkt hat eine hohe Qualität.", meaning: "This product is of high quality.", start: 289.42, end: 292.64 },
    { word: "Die beiden Möglichkeiten sind sehr ähnlich.", meaning: "The two possibilities are very similar.", start: 292.7, end: 295.9 },
    { word: "Insgesamt macht alles einen guten Eindruck.", meaning: "Overall, everything makes a good impression.", start: 296, end: 298.38 },
  ],
};
